Repository darkhyper24/melodify, pull requests merged in 2025-05, with the labels that each got.

#45 added full reviews and favourites functionality
  back/src/controllers/reviewController.ts
  back/src/controllers/songController.ts
  back/src/routes/songRoutes.ts
  front/src/api/reviews.ts
  front/src/api/songs.ts
  front/src/app/(pages)/user/album/[id]/page.tsx
  front/src/app/(pages)/user/playlist/[id]/page.tsx
  front/src/components/StarRating.tsx
  front/src/components/playerController.tsx
Labels: enhancement, frontend, backend

#46 Removed playlists from search and fixed song cover issue while seaching
  back/src/controllers/searchController.ts
  back/src/index.ts
  back/src/models/search.ts
  back/src/routes/searchRoutes.ts
  front/src/api/search.ts
  front/src/app/(pages)/search/page.tsx
  front/src/components/Navbar.tsx
  front/src/components/SearchResults.tsx
  front/src/components/SongRow.tsx
  front/src/hooks/useSearch.ts
Labels: enhancement, frontend, backend

#48 trying to fix refresh tokens handling and initial caching
  front/bun.lock
  front/package-lock.json
  front/package.json
  front/public/manifest.json
  front/public/sw.js
  front/src/api/albumDetails.ts
  front/src/api/artistAlbums.ts
  front/src/api/artists.ts
  front/src/api/axiosConfig.ts
  front/src/api/login.ts
  front/src/api/playlist.ts
  front/src/api/profile.ts
  front/src/api/reviews.ts
  front/src/api/search.ts
  front/src/api/signup.ts
  front/src/api/songs.ts
  front/src/api/user.ts
  front/src/app/(auth)/login/page.tsx
  front/src/app/(auth)/logout/page.tsx
  front/src/app/(auth)/signup/page.tsx
  front/src/app/layout.tsx
  front/src/app/metadata.ts
  front/src/components/AuthRedirect.tsx
  front/src/components/OfflineIndicator.tsx
  front/src/components/ServiceWorkerRegistry.tsx
  front/src/components/logout.tsx
  front/src/providers/PlayerProvider.tsx
  front/src/providers/ReactQueryProvider.tsx
Labels: frontend

#49 trying to fix deployment
  back/wrangler.jsonc
Labels: bug

#50 yarab
  back/package-lock.json
  back/package.json
  back/wrangler.jsonc
Labels: bug

#51 PLEAAAASE
  back/public/.gitkeep
  back/wrangler.jsonc
Labels: bug

#52 please deploy b2a
  back/public/hello.html
  back/wrangler.jsonc
Labels: bug

#53 ya moshl
  back/wrangler.jsonc
Labels: bug

#54 a5iran tm tsli7 deployment elback
  back/bun.lock
Labels: bug
