Repository darkhyper24/melodify, pull requests merged in 2025-04, with the labels that each got.

#26 added avatar icon for homepage/fixed error in profile page avatar success massage
  front/src/app/profile/page.tsx
  front/src/components/Navbar.tsx
  front/src/components/ProfileDropdown.tsx
  project/src/controllers/homeController.ts
  project/src/index.ts
  project/src/routes/homeRoutes.ts
Labels: bug, frontend, backend

#27 added crud operations for albums and respective endpoints
  Documentation/Melodify_OpenAPI.yaml
  project/src/controllers/albumController.ts
  project/src/routes/albumRoutes.ts
Labels: backend

#29 added content management for songs
  Documentation/Melodify_OpenAPI.yaml
  project/src/controllers/albumController.ts
  project/src/controllers/songController.ts
  project/src/index.ts
  project/src/models/song.ts
  project/src/routes/songRoutes.ts
Labels: backend

#30 adjusting songs schema and displaying data for songs page endpoint
  project/src/controllers/songController.ts
  project/src/models/song.ts
  project/src/routes/songRoutes.ts
Labels: enhancement, backend

#31 added cover art for each uploaded song.
  Documentation/Melodify_OpenAPI.yaml
  project/src/controllers/songController.ts
Labels: backend

#28 Fixed Artist sign up and Oauth authentication (not fully)
  front/src/api/albumDetails.ts
  front/src/api/artistAlbums.ts
  front/src/api/login.ts
  front/src/api/signup.ts
  front/src/api/user.ts
  front/src/app/(auth)/login/page.tsx
  front/src/app/(auth)/signup/page.tsx
  front/src/app/album/[id]/page.tsx
  front/src/app/artist_homepage/page.tsx
  front/src/components/AddAlbumModal.tsx
  front/src/components/AuthRedirect.tsx
  front/src/components/UploadAlbumCoverModal.tsx
  front/src/components/UploadSongModal.tsx
  project/src/routes/albumRoutes.ts
Labels: enhancement, frontend

#33 solving conflicts
  Documentation/Melodify_OpenAPI.yaml
  project/src/controllers/songController.ts
  project/src/routes/songRoutes.ts
Labels: bug, backend

#35 Added Melodify logo, fixed song upload and inability to click an album in homepage
  back/.gitignore
  back/README.md
  back/bun.lock
  back/package-lock.json
  back/package.json
  back/schema.sql
  back/src/controllers/albumController.ts
  back/src/controllers/authenticationController.ts
  back/src/controllers/homeController.ts
  back/src/controllers/profileController.ts
  back/src/controllers/songController.ts
  back/src/index.ts
  back/src/middleware/authMiddleware.ts
  back/src/middleware/roleMiddleware.ts
  back/src/models/album.ts
  back/src/models/playedTrack.ts
  back/src/models/playlist.ts
  back/src/models/playlistSong.ts
  back/src/models/profile.ts
  back/src/models/schema.ts
  back/src/models/song.ts
  back/src/routes/albumRoutes.ts
  back/src/routes/authRoutes.ts
  back/src/routes/homeRoutes.ts
  back/src/routes/profileRoutes.ts
  back/src/routes/songRoutes.ts
  back/src/supabase/supabase.ts
  back/tsconfig.json
  back/wrangler.jsonc
  front/public/logo.png
  front/src/api/albumDetails.ts
  front/src/api/artists.ts
  front/src/app/(pages)/user/home/page.tsx
  front/src/components/Navbar.tsx
Labels: frontend

#37 added reviews functionality
  Documentation/Melodify_OpenAPI.yaml
  back/src/controllers/reviewController.ts
  back/src/index.ts
  back/src/models/review.ts
  back/src/models/song.ts
  back/src/routes/reviewRoutes.ts
Labels: backend

#39 added users playlists logic
  back/bun.lock
  back/src/controllers/playlistController.ts
  back/src/controllers/songController.ts
  back/src/index.ts
  back/src/models/playlist.ts
  back/src/models/playlistSong.ts
  back/src/models/schema.ts
  back/src/routes/playlistRoutes.ts
  back/src/routes/songRoutes.ts
  front/bun.lock
Labels: backend

#42 added playlist page
  front/src/api/playlist.ts
  front/src/app/(pages)/user/album/[id]/page.tsx
  front/src/app/(pages)/user/home/page.tsx
  front/src/app/(pages)/user/playlist/[id]/page.tsx
  front/src/components/AddToPlaylistModal.tsx
  front/src/components/CreatePlaylistModal.tsx
  front/src/components/playerController.tsx
  front/src/providers/PlayerProvider.tsx
Labels: frontend

#44 added favourite songs endpoints
  Documentation/Melodify_OpenAPI.yaml
  back/src/controllers/songController.ts
  back/src/routes/songRoutes.ts
Labels: backend
